name: "Сообщение об ошибке"
description: "Опишите обнаруженную проблему или баг"
labels: ["bug"]
body:
  - type: input
    id: bug_title
    attributes:
      label: "Краткое описание ошибки"
      placeholder: "Например: 'Кнопка отправки не работает'"
    validations:
      required: true

  - type: textarea
    id: bug_description
    attributes:
      label: "Подробное описание ошибки"
      description: "Опишите что происходит, что должно происходить и как воспроизвести ошибку"
      placeholder: |
        1. Шаг 1...
        2. Шаг 2...
        3. Ожидаемый результат...
        4. Фактический результат...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: "Окружение"
      description: "Укажите где происходит ошибка"
      placeholder: |
        • Устройство: [например, PC, iPhone 12]
        • ОС: [например, Windows 11, iOS 16]
        • Браузер: [например, Chrome 120, Firefox 115]
        • Версия приложения: [если применимо]
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: "Скриншоты/Видео"
      description: "Приложите скриншоты или видео ошибки (перетащите файлы или укажите ссылки)"
      placeholder: "https://example.com/screenshot.jpg"
    validations:
      required: false

  - type: textarea
    id: additional_info
    attributes:
      label: "Дополнительная информация"
      description: "Логи, ошибки консоли, системные логи и т.д."
      placeholder: "Код ошибки или сообщение из логов..."
    validations:
      required: false
