name: "Работа: Предложение работы"
description: "Заполните информацию о работе, которую хотите предложить."
labels: ["new work"]
body:
  - type: input
    id: creator_nickname
    attributes:
      label: "Ваш ник"
      placeholder: "Введите ваш никнейм"
    validations:
      required: true

  - type: input
    id: creator_link
    attributes:
      label: "Ссылка на вас"
      placeholder: "https://example.com/profile"
    validations:
      required: true

  - type: textarea
    id: preview_image
    attributes:
      label: "Ваше изображение (обязательно с ригом)"
      description: "Перетащите изображение сюда или укажите на него ссылку"
      placeholder: "Ссылка на изображение или перетащите файл"
    validations:
      required: true
